# Generated by Django 5.1.5 on 2025-01-27 14:12
# Миграции создают связь между базой данных и между приложением, соединяет их.
# В пакете migrations через терминал создаём файл:

# python manage.py makemigrations

# В пакете создастся файл 0001_initial.py. В нём более подробно описаны поля таблицы, а также создано ключевое поле ‘id’.
# Такое поле должно быть в каждой таблице.
# Запускаем миграции через терминал.

#python manage.py migrate

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название новости')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание новости')),
                ('text', models.TextField(verbose_name='Какие то новости')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
